export { DashboardPage } from './Dashboard'
export { ProjectsPage } from './Projects'
export { ProjectDetailPage } from './ProjectDetail'
export { ProjectFormPage } from './ProjectForm'
export { ArtifactsListPage } from './ArtifactsList'
export { ArtifactViewerPage } from './ArtifactViewer'
export { ArtifactFormPage } from './ArtifactForm'
export { SignoffsPage } from './Signoffs'
export { SignoffDetailPage } from './SignoffDetail'
export { InquiriesPage } from './Inquiries'
export { InquiryDetailPage } from './InquiryDetail'
export { InquiryFormPage } from './InquiryForm'
export { TicketFormPage } from './TicketForm'
export { LoginPage } from './Login'
export { GitHubSyncPage } from './GitHubSync'
export { SettingsPage } from './Settings'
export { AIAssistantPage } from './AIAssistant'
export { KanbanBoardPage } from './KanbanBoard'
export { GanttChartPage } from './GanttChart'
export { ResourceAllocationPage } from './ResourceAllocation'
export { AnalyticsDashboardPage } from './AnalyticsDashboard'
export { BudgetTrackingPage } from './BudgetTracking'
export { AutomatedReportsPage } from './AutomatedReports'



